select
'NEW AGREEMENT' 'STATUS'
,a.AGREEMENT_EXTERNAL_NO 'AGREEMENT_NO / APPLICATION_NO'
,a.AGREEMENT_DATE 'AGREEMENT_DATE / APPLICATION_DATE'
,a.CLIENT_NAME
,b.FA_REFF_NO_01 'PLAT_NO'
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.AGREEMENT_MAIN a
inner join IFINOPL.dbo.AGREEMENT_ASSET b
on (b.AGREEMENT_NO = a.AGREEMENT_NO)
where a.CRE_BY = 'job'

union all

select
'APPLICATION HOLD'
,a.APPLICATION_EXTERNAL_NO
,a.APPLICATION_DATE
,c.CLIENT_NAME
,b.FA_REFF_NO_01
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.APPLICATION_MAIN a
inner join IFINOPL.dbo.APPLICATION_ASSET b
on (b.APPLICATION_NO = a.APPLICATION_NO)
inner join IFINOPL.dbo.CLIENT_MAIN c
on (c.CODE = a.CLIENT_CODE)
where a.APPLICATION_STATUS = 'HOLD'
and a.IS_SIMULATION = '0'

union all

select
'APPLICATION on PROCESS'
,a.APPLICATION_EXTERNAL_NO
,a.APPLICATION_DATE
,c.CLIENT_NAME
,b.FA_REFF_NO_01
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.APPLICATION_MAIN a
inner join IFINOPL.dbo.APPLICATION_ASSET b
on (b.APPLICATION_NO = a.APPLICATION_NO)
inner join IFINOPL.dbo.CLIENT_MAIN c
on (c.CODE = a.CLIENT_CODE)
where a.APPLICATION_STATUS = 'ON PROCESS'
and a.IS_SIMULATION = '0'

union all

select
'APPLICATION APPROVE'
,a.APPLICATION_EXTERNAL_NO
,a.APPLICATION_DATE
,c.CLIENT_NAME
,b.FA_REFF_NO_01
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.APPLICATION_MAIN a
inner join IFINOPL.dbo.APPLICATION_ASSET b
on (b.APPLICATION_NO = a.APPLICATION_NO)
inner join IFINOPL.dbo.CLIENT_MAIN c
on (c.CODE = a.CLIENT_CODE)
where a.APPLICATION_STATUS = 'APPROVE'
and a.LEVEL_STATUS <> 'GO LIVE'
and a.IS_SIMULATION = '0'

union all

select
'APPLICATION GO LIVE / ALLOCATION'
,a.APPLICATION_EXTERNAL_NO
,a.APPLICATION_DATE
,c.CLIENT_NAME
,b.FA_REFF_NO_01
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.APPLICATION_MAIN a
inner join IFINOPL.dbo.APPLICATION_ASSET b
on (b.APPLICATION_NO = a.APPLICATION_NO)
inner join IFINOPL.dbo.CLIENT_MAIN c
on (c.CODE = a.CLIENT_CODE)
where a.APPLICATION_STATUS = 'GO LIVE'
and a.LEVEL_STATUS = 'ALLOCATION'
and a.IS_SIMULATION = '0'

union all

select
'APPLICATION REALIZATION HOLD'
,a.APPLICATION_EXTERNAL_NO
,a.APPLICATION_DATE
,c.CLIENT_NAME
,b.FA_REFF_NO_01
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.APPLICATION_MAIN a
inner join IFINOPL.dbo.APPLICATION_ASSET b
on (b.APPLICATION_NO = a.APPLICATION_NO)
inner join IFINOPL.dbo.CLIENT_MAIN c
on (c.CODE = a.CLIENT_CODE)
inner join IFINOPL.dbo.REALIZATION d
on (d.APPLICATION_NO = a.APPLICATION_NO)
where a.APPLICATION_STATUS = 'GO LIVE'
and d.STATUS = 'HOLD'
and a.IS_SIMULATION = '0'

union all

select
'APPLICATION REALIZATION on PROCESS'
,a.APPLICATION_EXTERNAL_NO
,a.APPLICATION_DATE
,c.CLIENT_NAME
,b.FA_REFF_NO_01
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.APPLICATION_MAIN a
inner join IFINOPL.dbo.APPLICATION_ASSET b
on (b.APPLICATION_NO = a.APPLICATION_NO)
inner join IFINOPL.dbo.CLIENT_MAIN c
on (c.CODE = a.CLIENT_CODE)
inner join IFINOPL.dbo.REALIZATION d
on (d.APPLICATION_NO  = a.APPLICATION_NO)
where a.APPLICATION_STATUS = 'GO LIVE'
and d.STATUS = 'ON PROCESS'
and a.IS_SIMULATION = '0'

union all

select
'APPLICATION REALIZATION VERIFICATION'
,a.APPLICATION_EXTERNAL_NO
,a.APPLICATION_DATE
,c.CLIENT_NAME
,b.FA_REFF_NO_01
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.APPLICATION_MAIN a
inner join IFINOPL.dbo.APPLICATION_ASSET b
on (b.APPLICATION_NO = a.APPLICATION_NO)
inner join IFINOPL.dbo.CLIENT_MAIN c
on (c.CODE = a.CLIENT_CODE)
inner join IFINOPL.dbo.REALIZATION d
on (d.APPLICATION_NO  = a.APPLICATION_NO)
where a.APPLICATION_STATUS = 'GO LIVE'
and d.STATUS = 'VERIFICATION'
and a.IS_SIMULATION = '0'

union all

select
'APPLICATION REALIZATION POST'
,a.APPLICATION_EXTERNAL_NO
,a.APPLICATION_DATE
,c.CLIENT_NAME
,b.FA_REFF_NO_01
,b.ASSET_NAME
,a.PERIODE
,b.HANDOVER_BAST_DATE
,a.CRE_DATE
from IFINOPL.dbo.APPLICATION_MAIN a
inner join IFINOPL.dbo.APPLICATION_ASSET b
on (b.APPLICATION_NO = a.APPLICATION_NO)
inner join IFINOPL.dbo.CLIENT_MAIN c
on (c.CODE = a.CLIENT_CODE)
inner join IFINOPL.dbo.REALIZATION d
on (d.APPLICATION_NO  = a.APPLICATION_NO)
where a.APPLICATION_STATUS = 'GO LIVE'
and d.STATUS = 'POST'
and a.IS_SIMULATION = '0';